# Generated by Django 5.1.1 on 2025-03-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='text',
            new_name='title',
        ),
    ]
